-- ============================================================================
-- Armstrong Arikat Research Terminal — seed data. Run after db/schema.sql.
-- Idempotent: re-running updates rows in place.
-- ============================================================================

-- --- Orchestrator + chart sub-agent --------------------------------------
insert into agents (key, name, kind, role, sort_order) values
  ('beth',  'BETH — Chief of Staff', 'orchestrator',
   'Dispatches specialists, aggregates findings, resolves conflicts, formats reports.', 0),
  ('chart', 'Chart Specialist', 'chart',
   'Generates Plotly/Recharts specs with plain-English explainers and PNG exports.', 99)
on conflict (key) do update
  set name = excluded.name, role = excluded.role, sort_order = excluded.sort_order;

-- --- 15 specialist analysts ----------------------------------------------
insert into agents (key, name, kind, role, sort_order) values
  ('morning_packet',     'Morning Packet Analyst',                'specialist',
   'Overnight wrap, pre-market movers, earnings recap.', 1),
  ('midday_tactical',    'Mid-Day Tactical Analyst',              'specialist',
   'Intraday attribution, flow color, afternoon catalysts.', 2),
  ('market_close',       'Market Close Analyst',                  'specialist',
   'Daily P&L, after-hours earnings, next-day setup.', 3),
  ('ai_datacenter',      'AI Data Center Buildout Specialist',    'specialist',
   'Hyperscaler capex, DC REITs, cooling, power distribution.', 4),
  ('energy_infra',       'Energy Infrastructure Specialist',      'specialist',
   'IPPs, nuclear/SMRs, gas turbines, grid equipment.', 5),
  ('training_chip',      'Training Chip Specialist',              'specialist',
   'NVDA roadmap, HBM, CoWoS, custom training silicon.', 6),
  ('inference_stack',    'Inference & AI Software Stack Specialist','specialist',
   'Inference silicon, vLLM, token economics.', 7),
  ('robotics',           'Robotics & Physical AI Specialist',     'specialist',
   'Humanoids, industrial automation, autonomous vehicles.', 8),
  ('quantum',            'Quantum Computing Specialist',          'specialist',
   'IONQ, RGTI, competing quantum approaches.', 9),
  ('tech_generalist',    'Technology / Software Generalist',      'specialist',
   'SaaS, cloud, internet platforms.', 10),
  ('healthcare_biotech', 'Healthcare Biotech Specialist',         'specialist',
   'Catalysts, clinical trials, FDA decisions.', 11),
  ('consumer_internet',  'Consumer / Internet Specialist',        'specialist',
   'DTC, e-commerce, digital advertising.', 12),
  ('macro_strategy',     'Macro Strategy Analyst',                'specialist',
   'Rates, the Fed, factor rotation.', 13),
  ('quant',              'Quantitative Analyst',                  'specialist',
   'Factor exposure, screens, momentum.', 14),
  ('alt_data',           'Alt Data Specialist',                   'specialist',
   'Web traffic, app downloads, credit-card panels.', 15)
on conflict (key) do update
  set name = excluded.name, role = excluded.role, sort_order = excluded.sort_order;

-- --- Compliance disclaimer (v1) ------------------------------------------
insert into disclaimers (version, body, active) values
  ('2026.1',
   'This material is produced by Armstrong Arikat Private Wealth Group for ' ||
   'informational purposes only. It is not investment advice, an offer, or a ' ||
   'solicitation to buy or sell any security. Opinions are generated by an ' ||
   'automated multi-agent research system and are subject to compliance review. ' ||
   'Past performance does not guarantee future results. Consult your advisor ' ||
   'before acting on any information herein.',
   true)
on conflict (version) do update set body = excluded.body, active = excluded.active;

-- --- Report distribution list --------------------------------------------
insert into report_recipients (email, name, active) values
  ('brian@cccballers.com', 'Brian', true)
on conflict (email) do update set active = excluded.active;
