"""BETH — the Chief-of-Staff orchestrator.

Two entry points, one specialist-dispatch core:

  generate_report(slot)  — full report: dispatch -> charts -> Top 50 -> synthesis.
  refresh_top50()        — the 15-minute engine poll: dispatch -> ingest -> re-rank.

The Top 50 ranking is owned entirely by `app.engine.top50` — Beth feeds it and
reads it back, so there is one ranking algorithm, not two.
"""

from __future__ import annotations

import asyncio
import json
import logging
import re
from datetime import datetime, timezone

from app.agents.base import build_context
from app.agents.chart_specialist import ChartSpecialist
from app.agents.citation_enforcer import enforcer as citation_enforcer
from app.agents.conflict_resolver import resolver as conflict_resolver
from app.agents.red_team import red_team
from app.agents.registry import SPECIALISTS, roster_for
from app.agents.verifier import verify_high_conviction
from app.engine.top50 import engine
from app.schemas import (
    ChartSpec,
    CitationReport,
    ConflictReport,
    NewIdea,
    Recommendation,
    RecommendationAction,
    RecommendationVerification,
    RedTeamCritique,
    Report,
    ReportSlot,
    SpecialistRecommendation,
    SpecialistReport,
    Top50Snapshot,
    VariantPerception,
)
from app.services import audit, market_data, specialist_recommendations
from app.services.duration import duration_for
from app.services.macro_calendar import macro_event_today

# Avoid rule — contrarian picks need strong evidence; otherwise the
# orchestrator drops them before engine ingest (safety net for the
# specialist's own self-policing instruction).
AVOID_EVIDENCE_FLOOR = 7

# Parseable tags emitted by Holloway and Whitlock at the start of every
# covered_names_commentary narrative. See their mandates in registry.py.
_RE_YIELD = re.compile(r"yield\s+(\d+(?:\.\d+)?)\s*%", re.I)
_RE_SAFETY = re.compile(r"safety\s+(\d+)\s*/\s*10", re.I)
_RE_MOS = re.compile(r"\bMoS\s+(-?\d+(?:\.\d+)?)\s*%", re.I)

# Specialist keys whose picks count as "growth/thematic" for Beth's
# orchestration rules (contrarian check, bull-skew detection).
GROWTH_THEMATIC_KEYS: set[str] = {
    "ai_datacenter",
    "training_chip",
    "inference_stack",
    "robotics",
    "quantum",
    "tech_generalist",
    "consumer_internet",
}

# Trigger threshold for the bull-skew rule.
HIGH_CONVICTION = 8       # Rule 1: any single growth pick >= this fires contrarian.
BULL_SKEW_FLOOR = 7       # Rule 4: count of growth picks >= this triggers when >= count.
BULL_SKEW_COUNT = 4

logger = logging.getLogger("beth")

DISCLAIMER = (
    "This material is produced by Armstrong Arikat Private Wealth Group for internal "
    "research purposes only. It is not investment advice, an offer, or a solicitation "
    "to buy or sell any security. Opinions are generated by an automated multi-agent "
    "research system and are subject to compliance review. Past performance does not "
    "guarantee future results."
)

_BETH_SYSTEM = """\
You are BETH, Chief of Staff and research orchestrator at Armstrong Arikat Private
Wealth Group. You report to Brian, the Portfolio Manager. Your 15 specialists have
each filed a structured report. Synthesize them for Brian.

Your job:
- Write a tight executive summary (2-4 paragraphs) of the research window.
- Explicitly surface DISAGREEMENTS between specialists and give your adjudication.
- Escalate any risk flags the specialists raised that Brian must see.
- Tone: measured, dry, professional, no hype. This is research, not advice.

Respond with ONLY a JSON object:
{
  "title": "report title",
  "summary": "executive summary, conflict adjudication, escalated risk flags"
}
"""

_SLOT_TITLES = {
    ReportSlot.market_prep: "Market Prep — 7:30 AM",
    ReportSlot.mid_day: "Mid-Day Update — 11:00 AM",
    ReportSlot.market_close: "Market Close — 1:30 PM",
}


class Beth:
    """The orchestrator. One instance per call is fine; ranking state lives in the engine."""

    def __init__(self) -> None:
        self.chart_specialist = ChartSpecialist()

    # -- specialist dispatch (shared core) ----------------------------------
    async def dispatch(
        self, slot: ReportSlot, *, market_brief: str | None = None
    ) -> list[SpecialistReport]:
        """Run the slot's specialist roster concurrently; isolate failures."""
        brief = market_brief or self._default_brief(slot)
        roster = roster_for(slot)
        logger.info("BETH dispatching %d specialists for %s", len(roster), slot.value)

        context = build_context(slot=slot, market_brief=brief)
        results = await asyncio.gather(
            *(spec.run(context) for spec in roster),
            return_exceptions=True,
        )
        outputs: list[SpecialistReport] = []
        for spec, res in zip(roster, results):
            if isinstance(res, Exception):
                logger.warning("Specialist %s failed: %s", spec.key, res)
            else:
                outputs.append(res)
        return outputs

    # -- full report --------------------------------------------------------
    async def generate_report(
        self, slot: ReportSlot, *, market_brief: str | None = None
    ) -> Report:
        outputs = await self.dispatch(slot, market_brief=market_brief)

        # Citation Enforcement runs BEFORE the engine ingests anything, so in
        # strict mode sanitized text flows downstream. In default (non-strict)
        # mode, outputs are unchanged and only the citation_reports populate.
        citation_reports = await self._enforce_citations(outputs)

        # Drop contrarian+weak picks from outputs[].new_ideas before engine
        # ingest. Specialists are instructed to self-police this; the filter is
        # the safety net. Drops audit-log to .audit/positioning_filter.jsonl.
        self._apply_positioning_filter(outputs)

        # Epistemic humility: any new_idea without a populated epistemic_check
        # gets conviction_1_10 downgraded by 2 (clamped to >= 1). Runs BEFORE
        # PSV so verify_high_conviction's conviction>=8 threshold sees the
        # downgraded value. Audit-log every downgrade.
        self._apply_epistemic_downgrade(outputs)

        # Hindsight test on conviction>=8 picks (after epistemic downgrade).
        # Missing test -> conviction -2; publishable=false -> drop pick.
        self._apply_hindsight_test(outputs)

        # Calibration check — warn on specialists filing >=3 picks all at
        # conviction>=8. Audit-only; doesn't mutate conviction.
        self._check_calibration(outputs)

        # Five work items run concurrently:
        #   - render charts requested by specialists
        #   - PSV verifier on conviction>=8 ideas
        #   - Beth's "focused contrarian" pass (Value Investor again, if
        #     growth/thematic team produced high-conviction picks or skewed bullish)
        #   - persist every new_idea as a SpecialistRecommendation row
        #   - resolve specialist disagreements per ticker
        charts, verifications, bear_case, _, conflicts = await asyncio.gather(
            self._render_charts(outputs),
            self._verify_high_conviction(outputs),
            self._maybe_focused_contrarian(outputs, slot=slot),
            self._log_recommendations(outputs),
            conflict_resolver.resolve(outputs),
        )

        # Feed the Top 50 engine and read the ranking back — single source.
        engine.ingest(outputs)
        snapshot = await engine.rebuild()
        await self._enrich_top50(snapshot, outputs)
        recommendations = self._recommendations_from(snapshot)

        # Macro event-day rule: on FOMC / CPI / NFP days, Fixed Income leads.
        macro_event = macro_event_today()
        lead_key = "fixed_income" if macro_event else None

        # Red Team attacks the top conviction picks in parallel with the
        # synthesis turn — independent inputs (synthesize reads `outputs`,
        # Red Team reads the snapshot's ranked entries).
        (title, summary), red_team_critiques = await asyncio.gather(
            self._synthesize(slot, outputs),
            red_team.attack(snapshot),
        )

        return Report(
            slot=slot,
            title=title,
            summary=summary,
            recommendations=recommendations,
            charts=charts,
            specialist_reports=outputs,
            verifications=verifications,
            citation_reports=citation_reports,
            red_team_critiques=red_team_critiques,
            conflicts=conflicts,
            lead_specialist_key=lead_key,
            bear_case_addendum=bear_case,
            macro_event=macro_event,
            disclaimer=DISCLAIMER,
            generated_at=datetime.now(timezone.utc),
        )

    # -- 15-minute Top 50 poll ---------------------------------------------
    async def refresh_top50(self) -> Top50Snapshot:
        """Poll specialists and re-rank the Top 50. Driven by the scheduler."""
        outputs = await self.dispatch(ReportSlot.mid_day)
        engine.ingest(outputs)
        snapshot = await engine.rebuild()
        await self._enrich_top50(snapshot, outputs)
        return snapshot

    # -- pipeline stages ----------------------------------------------------
    @staticmethod
    async def _verify_high_conviction(
        outputs: list[SpecialistReport],
    ) -> list[RecommendationVerification]:
        """PSV runs only on `new_ideas` with conviction>=8. One task per specialist."""
        jobs = [
            verify_high_conviction(
                sr.new_ideas, agent_key=sr.agent_key, persona=sr.specialist
            )
            for sr in outputs
        ]
        nested = await asyncio.gather(*jobs, return_exceptions=True)
        flat: list[RecommendationVerification] = []
        for result in nested:
            if isinstance(result, list):
                flat.extend(result)
            elif isinstance(result, Exception):
                logger.warning("Verifier batch failed: %s", result)
        return flat

    @staticmethod
    def _apply_epistemic_downgrade(outputs: list[SpecialistReport]) -> int:
        """Downgrade conviction by 2 on every new_idea missing an epistemic_check.

        A check is "incomplete" if any required text field is blank. Lists may
        be empty (an honest "I have nothing to add" is acceptable for
        unverified_data_points).
        """
        downgrades = 0
        for sr in outputs:
            for idea in sr.new_ideas:
                ec = idea.epistemic_check
                complete = (
                    ec is not None
                    and ec.what_would_change_my_mind.strip()
                    and ec.most_likely_way_im_wrong.strip()
                    and ec.counter_arguments_sought.strip()
                    and ec.conviction_calibration.strip()
                )
                if complete:
                    continue
                original = idea.conviction_1_10
                idea.conviction_1_10 = max(1, original - 2)
                downgrades += 1
                audit.log_event(
                    "epistemic_downgrade",
                    {
                        "agent_key": sr.agent_key,
                        "specialist": sr.specialist,
                        "ticker": idea.ticker,
                        "original_conviction": original,
                        "downgraded_conviction": idea.conviction_1_10,
                        "reason": (
                            "epistemic_check missing"
                            if ec is None
                            else "epistemic_check incomplete"
                        ),
                        "thesis": idea.thesis[:240],
                    },
                )
        return downgrades

    @staticmethod
    def _apply_hindsight_test(outputs: list[SpecialistReport]) -> tuple[int, int]:
        """Two-tier enforcement on conviction>=8 picks:

        1. ``hindsight_test`` is None or incomplete -> conviction -2 (audit logged).
        2. ``publishable=False`` -> pick dropped entirely from new_ideas
           (specialist's self-flag is respected).

        Runs after _apply_epistemic_downgrade so the conviction>=8 gate
        reflects honest conviction.
        """
        downgraded = 0
        dropped = 0
        for sr in outputs:
            kept: list[NewIdea] = []
            for idea in sr.new_ideas:
                if idea.conviction_1_10 < 8:
                    kept.append(idea)
                    continue
                ht = idea.hindsight_test
                # Drop on explicit self-flag.
                if ht is not None and ht.publishable is False:
                    dropped += 1
                    audit.log_event(
                        "hindsight_test",
                        {
                            "agent_key": sr.agent_key,
                            "specialist": sr.specialist,
                            "ticker": idea.ticker,
                            "action": "dropped",
                            "reason": "publishable=false self-flag",
                            "loss_scenario_reason": ht.loss_scenario_reason[:200],
                            "thesis": idea.thesis[:240],
                        },
                    )
                    continue
                # Downgrade on missing or incomplete test.
                complete = (
                    ht is not None
                    and ht.loss_scenario_reason.strip()
                    and ht.win_scenario_catalyst.strip()
                )
                if not complete:
                    original = idea.conviction_1_10
                    idea.conviction_1_10 = max(1, original - 2)
                    downgraded += 1
                    audit.log_event(
                        "hindsight_test",
                        {
                            "agent_key": sr.agent_key,
                            "specialist": sr.specialist,
                            "ticker": idea.ticker,
                            "action": "downgraded",
                            "original_conviction": original,
                            "downgraded_conviction": idea.conviction_1_10,
                            "reason": (
                                "hindsight_test missing"
                                if ht is None
                                else "hindsight_test incomplete"
                            ),
                        },
                    )
                kept.append(idea)
            if dropped:
                sr.new_ideas = kept
        return downgraded, dropped

    @staticmethod
    def _check_calibration(outputs: list[SpecialistReport]) -> int:
        """Audit-log specialists with >=3 picks all at conviction>=8. No mutation."""
        warned = 0
        for sr in outputs:
            ideas = sr.new_ideas
            if len(ideas) < 3:
                continue
            if all(i.conviction_1_10 >= 8 for i in ideas):
                warned += 1
                audit.log_event(
                    "calibration_warning",
                    {
                        "agent_key": sr.agent_key,
                        "specialist": sr.specialist,
                        "pick_count": len(ideas),
                        "all_convictions": [i.conviction_1_10 for i in ideas],
                        "tickers": [i.ticker for i in ideas],
                        "rule": "every new_idea at conviction>=8 — calibration likely broken",
                    },
                )
        return warned

    @staticmethod
    def _apply_positioning_filter(outputs: list[SpecialistReport]) -> int:
        """Drop contrarian+weak new_ideas from outputs in place. Audits each drop."""
        dropped = 0
        for sr in outputs:
            kept: list[NewIdea] = []
            for idea in sr.new_ideas:
                mp = idea.market_positioning
                if (
                    mp is not None
                    and mp.variant_perception == VariantPerception.contrarian
                    and mp.evidence_strength < AVOID_EVIDENCE_FLOOR
                ):
                    audit.log_event(
                        "positioning_filter",
                        {
                            "agent_key": sr.agent_key,
                            "specialist": sr.specialist,
                            "ticker": idea.ticker,
                            "rule": f"contrarian + evidence_strength < {AVOID_EVIDENCE_FLOOR}",
                            "evidence_strength": mp.evidence_strength,
                            "crowding_score": mp.crowding_score,
                            "thesis": idea.thesis[:240],
                        },
                    )
                    dropped += 1
                    continue
                kept.append(idea)
            if dropped:
                sr.new_ideas = kept
        return dropped

    @staticmethod
    async def _log_recommendations(outputs: list[SpecialistReport]) -> int:
        """Append every specialist's new_ideas to the SpecialistRecommendation store.

        Each new_idea becomes one row with entry_price = current snapshot price
        (batch-fetched) and entry_timestamp = filing time. Lifecycle outcome
        columns stay None until the trade is closed via /api/specialist-
        recommendations/{id}/close.
        """
        if not outputs:
            return 0
        tickers: set[str] = set()
        for sr in outputs:
            for idea in sr.new_ideas:
                if idea.ticker:
                    tickers.add(idea.ticker.upper())
        quotes = await market_data.get_quotes(sorted(tickers)) if tickers else {}

        written = 0
        for sr in outputs:
            for idea in sr.new_ideas:
                ticker = idea.ticker.upper() if idea.ticker else ""
                if not ticker:
                    continue
                quote = quotes.get(ticker)
                # Populate target_price + stop_loss from the probabilistic
                # forecast when present: base_case is the target, bear_case is
                # the stop. Assumptions surface key_uncertainties + key_risk.
                target_price: float | None = None
                stop_loss: float | None = None
                assumptions: list[str] = []
                if idea.forecast is not None:
                    target_price = idea.forecast.base_case_50pct.price
                    stop_loss = idea.forecast.bear_case_25pct.price
                    assumptions.extend(idea.forecast.key_uncertainties)
                if idea.key_risk:
                    assumptions.append(idea.key_risk)

                # Market positioning overlay + consensus delta.
                variant = None
                crowding = None
                evidence = None
                consensus_target = None
                consensus_delta = None
                if idea.market_positioning is not None:
                    mp = idea.market_positioning
                    variant = mp.variant_perception
                    crowding = mp.crowding_score
                    evidence = mp.evidence_strength
                    consensus_target = mp.consensus_target
                    if (
                        consensus_target
                        and idea.forecast
                        and consensus_target != 0
                    ):
                        team_target = idea.forecast.base_case_50pct.price
                        consensus_delta = round(
                            (team_target - consensus_target) / consensus_target * 100, 4
                        )

                rec = SpecialistRecommendation(
                    agent_key=sr.agent_key,
                    specialist=sr.specialist,
                    ticker=ticker,
                    action=RecommendationAction.long,  # new_ideas are bullish pitches
                    conviction_1_10=idea.conviction_1_10,
                    time_horizon=idea.time_horizon,
                    thesis_summary=idea.thesis,
                    entry_price=(quote.price if quote else None),
                    entry_timestamp=sr.timestamp or datetime.now(timezone.utc),
                    target_price=target_price,
                    stop_loss=stop_loss,
                    thesis_assumptions=assumptions,
                    variant_perception=variant,
                    crowding_score=crowding,
                    evidence_strength=evidence,
                    consensus_target=consensus_target,
                    consensus_target_vs_team_target_pct=consensus_delta,
                )
                specialist_recommendations.append(rec)
                written += 1
        return written

    @staticmethod
    async def _enforce_citations(
        outputs: list[SpecialistReport],
    ) -> list[CitationReport]:
        """Run the Citation Enforcement Agent on every specialist filing."""
        reports = await asyncio.gather(
            *(citation_enforcer.enforce(sr) for sr in outputs),
            return_exceptions=True,
        )
        out: list[CitationReport] = []
        for r in reports:
            if isinstance(r, CitationReport):
                out.append(r)
            elif isinstance(r, Exception):
                logger.warning("Citation enforcement failed: %s", r)
        return out

    @staticmethod
    async def _maybe_focused_contrarian(
        outputs: list[SpecialistReport], *, slot: ReportSlot
    ) -> SpecialistReport | None:
        """Beth's contrarian-check rules:

        - Rule 1: any growth/thematic pick with conviction >= HIGH_CONVICTION (8)
          triggers a focused bear-case check on that name.
        - Rule 4: when growth/thematic specialists collectively file >= BULL_SKEW_COUNT
          picks at conviction >= BULL_SKEW_FLOOR, dispatch a dedicated bear case.

        Both trigger the same downstream action — one extra Value Investor pass
        with a focused contrarian context. Returns None when neither fires.
        """
        growth_picks: list[tuple[str, str, int, str]] = []
        bull_skew_picks: list[tuple[str, str, int]] = []
        for sr in outputs:
            if sr.agent_key not in GROWTH_THEMATIC_KEYS:
                continue
            for idea in sr.new_ideas:
                if idea.conviction_1_10 >= HIGH_CONVICTION:
                    growth_picks.append(
                        (sr.specialist, idea.ticker, idea.conviction_1_10, idea.thesis)
                    )
                if idea.conviction_1_10 >= BULL_SKEW_FLOOR:
                    bull_skew_picks.append((sr.specialist, idea.ticker, idea.conviction_1_10))

        bull_skew = len(bull_skew_picks) >= BULL_SKEW_COUNT
        if not growth_picks and not bull_skew:
            return None

        spec = SPECIALISTS.get("value_investor")
        if spec is None:
            logger.warning("value_investor specialist missing — skipping contrarian pass.")
            return None

        triggers: list[str] = []
        if growth_picks:
            triggers.append(f"{len(growth_picks)} growth/thematic pick(s) at conviction>=8")
        if bull_skew:
            triggers.append(
                f"team consensus skews bullish ({len(bull_skew_picks)} picks at "
                f"conviction>={BULL_SKEW_FLOOR})"
            )

        picks_block = "\n".join(
            f"- {persona}: {ticker} (conviction {conv}/10) — {thesis}"
            for persona, ticker, conv, thesis in growth_picks[:12]
        ) or "(no single name at conviction>=8 — the bull-skew rule fired)"

        bull_block = "\n".join(
            f"- {persona}: {ticker} ({conv}/10)"
            for persona, ticker, conv in bull_skew_picks[:20]
        )

        focus = (
            f"FOCUSED CONTRARIAN CHECK — triggered by: {'; '.join(triggers)}.\n\n"
            "The growth/thematic side of the team has filed conviction picks that "
            "require your bear-case rigor BEFORE this report reaches Brian. Do "
            "NOT repeat your general-pass output. For each high-conviction name "
            "below, produce the contrarian read: consensus thesis as you read "
            "it, your counter-view, the valuation risk, the downside scenario, "
            "and a verdict (defensible | overhyped | trap).\n\n"
            f"HIGH-CONVICTION GROWTH PICKS (rule 1):\n{picks_block}\n\n"
            f"FULL BULL-SKEW ROSTER (rule 4):\n{bull_block}\n\n"
            "Output channels — use these fields in your standard SpecialistReport:\n"
            "- key_takeaway: one sentence on the most stretched name and your "
            "  overall verdict on the bullish skew.\n"
            "- covered_names_commentary: one entry per checked ticker; narrative "
            "  is your contrarian view + verdict; action is 'avoid' | 'watch' | 'hold'.\n"
            "- new_ideas: leave empty unless you have a SHORT-side equivalent value "
            "  setup that pairs with one of these names.\n"
            "- risk_flags: any name you judge a trap."
        )

        context = build_context(
            slot=slot, market_brief=Beth._default_brief(slot), focus=focus
        )
        try:
            return await spec.run(context)
        except Exception as exc:
            logger.warning("Focused contrarian pass failed: %s", exc)
            return None

    async def _render_charts(self, outputs: list[SpecialistReport]) -> list[ChartSpec]:
        jobs = [
            self.chart_specialist.render(
                out.chart_request, requested_by=out.specialist, agent_key=out.agent_key
            )
            for out in outputs
            if out.chart_request is not None
        ]
        if not jobs:
            return []
        done = await asyncio.gather(*jobs, return_exceptions=True)
        return [c for c in done if isinstance(c, ChartSpec)]

    @staticmethod
    async def _enrich_top50(snapshot: Top50Snapshot, outputs: list[SpecialistReport]) -> None:
        """Overlay per-ticker specialist signal onto each Top 50 entry — in place.

        - dividend_yield / dividend_safety from Holloway's tag prefix.
        - value_score (margin of safety %) from Whitlock's tag prefix.
        - duration_sensitivity from Polygon sic_description -> duration_for().

        The two tag prefixes are spelled out in each specialist's mandate; if
        the LLM departs from the format we degrade to None silently.
        """
        holloway = Beth._coverage_lookup(outputs, "dividend_aristocrat")
        whitlock = Beth._coverage_lookup(outputs, "value_investor")

        # Pull sector details once per ticker — get_ticker_details is cached.
        sectors = await asyncio.gather(
            *(market_data.get_ticker_details(e.ticker) for e in snapshot.entries),
            return_exceptions=True,
        )

        for entry, details in zip(snapshot.entries, sectors):
            # Holloway overlays
            text = holloway.get(entry.ticker.upper())
            if text:
                m = _RE_YIELD.search(text)
                if m:
                    try:
                        entry.dividend_yield = float(m.group(1))
                    except ValueError:
                        pass
                m = _RE_SAFETY.search(text)
                if m:
                    try:
                        entry.dividend_safety = int(m.group(1))
                    except ValueError:
                        pass
            # Whitlock overlay
            text = whitlock.get(entry.ticker.upper())
            if text:
                m = _RE_MOS.search(text)
                if m:
                    try:
                        entry.value_score = float(m.group(1))
                    except ValueError:
                        pass
            # Duration sensitivity from sector
            if isinstance(details, dict):
                entry.duration_sensitivity = duration_for(details.get("sic_description"))

    @staticmethod
    def _coverage_lookup(
        outputs: list[SpecialistReport], agent_key: str
    ) -> dict[str, str]:
        """ticker.upper() -> narrative text for one specialist's coverage."""
        for sr in outputs:
            if sr.agent_key != agent_key:
                continue
            lookup: dict[str, str] = {}
            for cn in sr.covered_names_commentary:
                if cn.ticker:
                    lookup[cn.ticker.upper()] = cn.narrative
            return lookup
        return {}

    @staticmethod
    def _recommendations_from(snapshot: Top50Snapshot) -> list[Recommendation]:
        """Map engine Top 50 entries onto the API-facing Recommendation model."""
        return [
            Recommendation(
                rank=e.rank,
                symbol=e.ticker,
                name=e.company_name,
                price=e.price,
                dailyPct=e.day_change_pct,
                ytdPct=e.ytd_change_pct,
                conviction=max(1, min(10, round(e.conviction_avg))),
                thesis=e.thesis_summary,
                leadSpecialist=e.lead_specialist,
                lastUpdated=snapshot.snapshot_time,
            )
            for e in snapshot.entries
        ]

    async def _synthesize(
        self, slot: ReportSlot, outputs: list[SpecialistReport]
    ) -> tuple[str, str]:
        if not outputs:
            return _SLOT_TITLES[slot], "No specialist findings were produced for this window."

        digest = json.dumps(
            [
                {
                    "specialist": o.specialist,
                    "key_takeaway": o.key_takeaway,
                    "top_ideas": [
                        {"ticker": idea.ticker, "conviction": idea.conviction_1_10}
                        for idea in o.new_ideas[:5]
                    ],
                    "risk_flags": o.risk_flags,
                }
                for o in outputs
            ],
            indent=2,
        )
        from app.services.anthropic_client import call_agent

        reply = await call_agent(
            system_prompt=_BETH_SYSTEM,
            user_message=f"Report window: {slot.value}\n\nSpecialist filings:\n{digest}",
            temperature=0.4,
            agent_name="beth:synthesis",
            downstream_consumers=["report.summary", "email_render"],
        )
        data = reply.as_json()
        return data.get("title", _SLOT_TITLES[slot]), data.get("summary", "")

    @staticmethod
    def _default_brief(slot: ReportSlot) -> str:
        """Placeholder brief until the market-data pipeline feeds Beth live context.

        TODO(step 3): replace with a real brief assembled from Polygon snapshots,
        the economic calendar, and the overnight earnings tape.
        """
        return (
            f"[{slot.value}] No live market brief wired yet. Specialists should reason "
            "from their coverage universe and flag where live data is required."
        )
