"""BETH — the Chief-of-Staff orchestrator.

Pipeline for one report:
  1. Build a market brief for the window.
  2. Dispatch the specialist roster concurrently (one bad specialist never kills
     the report — failures are logged and skipped).
  3. Route every specialist chart request to the Chart Specialist.
  4. Aggregate specialist `new_ideas` into a ranked Top 50, resolving duplicate
     coverage by conviction score (1-10).
  5. Run Beth's own synthesis turn — executive summary, conflict adjudication,
     and escalation of specialist risk flags.
  6. Return a Report; persistence + email happen downstream.
"""

from __future__ import annotations

import asyncio
import json
import logging
from datetime import datetime, timezone

from app.agents.base import build_context
from app.agents.chart_specialist import ChartSpecialist
from app.agents.registry import roster_for
from app.schemas import (
    ChartSpec,
    Recommendation,
    Report,
    ReportSlot,
    SpecialistReport,
)
from app.services import market_data

logger = logging.getLogger("beth")

DISCLAIMER = (
    "This material is produced by Armstrong Arikat Private Wealth Group for internal "
    "research purposes only. It is not investment advice, an offer, or a solicitation "
    "to buy or sell any security. Opinions are generated by an automated multi-agent "
    "research system and are subject to compliance review. Past performance does not "
    "guarantee future results."
)

_BETH_SYSTEM = """\
You are BETH, Chief of Staff and research orchestrator at Armstrong Arikat Private
Wealth Group. You report to Brian, the Portfolio Manager. Your 15 specialists have
each filed a structured report. Synthesize them for Brian.

Your job:
- Write a tight executive summary (2-4 paragraphs) of the research window.
- Explicitly surface DISAGREEMENTS between specialists and give your adjudication.
- Escalate any risk flags the specialists raised that Brian must see.
- Tone: measured, dry, professional, no hype. This is research, not advice.

Respond with ONLY a JSON object:
{
  "title": "report title",
  "summary": "executive summary, conflict adjudication, escalated risk flags"
}
"""

_SLOT_TITLES = {
    ReportSlot.market_prep: "Market Prep — 7:30 AM",
    ReportSlot.mid_day: "Mid-Day Update — 11:00 AM",
    ReportSlot.market_close: "Market Close — 1:30 PM",
}


class Beth:
    """The orchestrator. One instance per process is fine; runs are stateless."""

    def __init__(self) -> None:
        self.chart_specialist = ChartSpecialist()

    async def generate_report(
        self, slot: ReportSlot, *, market_brief: str | None = None
    ) -> Report:
        brief = market_brief or self._default_brief(slot)
        roster = roster_for(slot)
        logger.info("BETH dispatching %d specialists for %s", len(roster), slot.value)

        # 2. Dispatch specialists concurrently; isolate failures.
        context = build_context(slot=slot, market_brief=brief)
        results = await asyncio.gather(
            *(spec.run(context) for spec in roster),
            return_exceptions=True,
        )
        outputs: list[SpecialistReport] = []
        for spec, res in zip(roster, results):
            if isinstance(res, Exception):
                logger.warning("Specialist %s failed: %s", spec.key, res)
            else:
                outputs.append(res)

        # 3. Charts.
        charts = await self._render_charts(outputs)

        # 4. Aggregate the Top 50.
        recommendations = await self._rank_recommendations(outputs)

        # 5. BETH synthesis.
        title, summary = await self._synthesize(slot, outputs)

        return Report(
            slot=slot,
            title=title,
            summary=summary,
            recommendations=recommendations,
            charts=charts,
            specialist_reports=outputs,
            disclaimer=DISCLAIMER,
            generated_at=datetime.now(timezone.utc),
        )

    # -- pipeline stages ----------------------------------------------------
    async def _render_charts(self, outputs: list[SpecialistReport]) -> list[ChartSpec]:
        jobs = [
            self.chart_specialist.render(
                out.chart_request, requested_by=out.specialist, agent_key=out.agent_key
            )
            for out in outputs
            if out.chart_request is not None
        ]
        if not jobs:
            return []
        done = await asyncio.gather(*jobs, return_exceptions=True)
        return [c for c in done if isinstance(c, ChartSpec)]

    async def _rank_recommendations(
        self, outputs: list[SpecialistReport]
    ) -> list[Recommendation]:
        """Dedup by ticker (keep the highest-conviction sponsor), rank, take Top 50."""
        # ticker -> (conviction_1_10, thesis, sponsoring persona)
        best: dict[str, tuple[int, str, str]] = {}
        for out in outputs:
            for idea in out.new_ideas:
                sym = idea.ticker.upper()
                if sym not in best or idea.conviction_1_10 > best[sym][0]:
                    best[sym] = (idea.conviction_1_10, idea.thesis, out.specialist)

        ranked = sorted(best.items(), key=lambda kv: kv[1][0], reverse=True)[:50]
        quotes = await market_data.get_quotes([sym for sym, _ in ranked])
        now = datetime.now(timezone.utc)

        recs: list[Recommendation] = []
        for i, (sym, (conviction, thesis, persona)) in enumerate(ranked, start=1):
            q = quotes.get(sym)
            recs.append(
                Recommendation(
                    rank=i,
                    symbol=sym,
                    name=sym,  # TODO(step 2 wiring): resolve from the `securities` table
                    price=q.price if q else None,
                    dailyPct=q.daily_pct if q else None,
                    ytdPct=q.ytd_pct if q else None,
                    conviction=conviction,
                    thesis=thesis,
                    leadSpecialist=persona,
                    lastUpdated=now,
                )
            )
        return recs

    async def _synthesize(
        self, slot: ReportSlot, outputs: list[SpecialistReport]
    ) -> tuple[str, str]:
        if not outputs:
            return _SLOT_TITLES[slot], "No specialist findings were produced for this window."

        digest = json.dumps(
            [
                {
                    "specialist": o.specialist,
                    "key_takeaway": o.key_takeaway,
                    "top_ideas": [
                        {"ticker": idea.ticker, "conviction": idea.conviction_1_10}
                        for idea in o.new_ideas[:5]
                    ],
                    "risk_flags": o.risk_flags,
                }
                for o in outputs
            ],
            indent=2,
        )
        from app.services.anthropic_client import call_agent

        reply = await call_agent(
            system_prompt=_BETH_SYSTEM,
            user_message=f"Report window: {slot.value}\n\nSpecialist filings:\n{digest}",
            temperature=0.4,
        )
        data = reply.as_json()
        return data.get("title", _SLOT_TITLES[slot]), data.get("summary", "")

    @staticmethod
    def _default_brief(slot: ReportSlot) -> str:
        """Placeholder brief until the market-data pipeline feeds Beth live context.

        TODO(step 3): replace with a real brief assembled from Polygon snapshots,
        the economic calendar, and the overnight earnings tape.
        """
        return (
            f"[{slot.value}] No live market brief wired yet. Specialists should reason "
            "from their coverage universe and flag where live data is required."
        )
